channels:
- bioconda
- conda-forge
dependencies:
- python=3.9.*
- pip=20.2.*

# Package to allow Jupyter Notebook or JupyterLab applications in one conda env to access other kernels (e.g. qiime2) 
- nb_conda_kernels=2.3.1

# Packages from bioconda for IB134L
- bwa=0.7.12
- samtools=1.3.1
- mafft=7.471
- emboss=6.6.0
- augustus=3.3.3
- raxml-ng=1.0.1
- structure=2.3.4
- paml=4.9
#- repeatmasker=4.0.9
- trimmomatic=0.39
- blast=2.12.0
- fastqc=0.11.9
- phyml=3.3.20200621
- sra-tools=2.11
- hisat2=2.2.1
- subread=2.0.1

# Packages for IB120/201/CCB210
- sympy=1.6.2

# Packages from bioconda for BioE-131, Fall 2020, Issue #1885
- bowtie2=2.4.2
- spades=3.14.1

# Packages from bioconda for BIO1B
- raxml=8.2.*
- muscle=3.8.*
- dendropy=4.4.*
- pip:
  - -r requirements.txt
