channels:
- bioconda
- conda-forge
dependencies:
- python=3.8.*
- pip=20.*

# Packages from bioconda for IB134L
- bwa=0.7.12 
- samtools=1.3.1 

# Packages from bioconda for BIO1B
- raxml=8.2.*
- muscle=3.8.*
- dendropy=4.4.*
- pip:
  - -r requirements.txt
